### ISSUE TITLE
Zarr Twitter feed

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/community#3]
Both issue ( https://github.com/zarr-developers/zarr/issues/444 ) and some of our discussion at the end of the meeting today made me think we might benefit from a Zarr Twitter handle. We could retweet blogposts related to Zarr, new releases, and other things of interest.

**Comment by joshmoore** [comment]
or `zarr_data` a la `pangeo_data`.

**Comment by alimanfoo** [comment]
...or maybe zarr_dev a la pandas_dev and dask_dev?

**Comment by joshmoore** [comment]
http://twitter.com/zarr_dev created today. Retweeted some historical tweets to seed the account and then commented on the ChanZuckerberg post.
