### ISSUE TITLE
Zarr Spec V3 high bandwidth call. 

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/community#33]
This is an issue to track the regular call to discuss and move forward the zarr spec v3. 

Those call are currently in alternance with the Zarr Community call (#1) , 

tl;dr:
weekly calls 

Topic: Zarr v3 dev
Time: Oct 9, 2020 02:00 PM Universal Time UTC

Join Zoom Meeting
https://us02web.zoom.us/j/89587548300?pwd=Z045VEdJWUM4UjgwaEcxUnV2UHVPdz09

Meeting ID: 895 8754 8300
Passcode: 024214
Find your local number: https://us02web.zoom.us/u/kdit3KfoKe

Agenda and notes: https://docs.google.com/document/d/16CFAM3VWTIugUMc8vGEi9bxHwtrvrqDePVNEHeDtMCs/edit?usp=sharing

**Comment by alimanfoo** [comment]
Hi all, today we discussed trying to reschedule the v3 spec development meetings to be friendlier to multiple time zones. If you are interested in attending future calls please could you respond to the following doodle poll:

https://doodle.com/poll/76syg3ycbuuyebdg

cc @Carreau @rabernat @jakirkham @DennisHeimbigner @joshmoore @ryan-williams @andrewfulton9 @sylvaincorlay @davidbrochart

(BTW unfortunately I will be on leave for the next call, but will be in attendance for following calls.)

**Comment by Carreau** [comment]
Looks like we have quasi quorum for friday 24th in 10 days. 

Juil 24 18:00-19:00 Paris time
Juil 24 5:00pm-6:00pm London
Juil 24 12:00pm-1:00pm EST
Juil 24 11:00am-12:00pm Central
Juil 24 10:00am-11:00pm Mountain
Juil 24 9:00am-10:00am Pacific

So let's move next meeting from the 22cd to the 24th, and make it 3h earlier.

**Comment by davidbrochart** [comment]
I can see July 22nd is convenient for almost everybody too. I might not be able to make it on Friday in the end, would it be possible to move the meeting to Wednesday?

**Comment by Carreau** [comment]
> I can see July 22nd is convenient for almost everybody too. I might not be able to make it on Friday in the end, would it be possible to move the meeting to Wednesday?

We've been moving this mostly to get quantstack and @sylvainCorlay involved, though the 22cd is the only day where he is unavailable. Let's try to get quantstack at least once it would be great, and then we can try to adjust. Is you a generic "not avail on Friday" or more a "not avail on the 24th?".

**Comment by davidbrochart** [comment]
Sorry, I had not refreshed the doodle, now I can see @SylvainCorlay is not available on Wednesday. He is available tomorrow though, is it too short notice? I might not be available this particular Friday only.

**Comment by Carreau** [comment]
We can try to do both I'm available, but we have to see how that affects others.

**Comment by jakirkham** [comment]
I think if we schedule it short notice we will wind up missing more people.

Does the time Matthias proposed on Friday not work for you David? If so, is this a one-off issue or a recurring one?

Also @joshmoore is [this time]( https://github.com/zarr-developers/community/issues/33#issuecomment-659760233 ) going to work for you? Noticed that you have it marked as a maybe.

**Comment by davidbrochart** [comment]
I might not be able to make it this coming Friday, the following ones should be fine.

**Comment by joshmoore** [comment]
@jakirkham : the Friday slot will _often_ work, though there will be times when I will need to miss for family reasons.

**Comment by jakirkham** [comment]
Fair enough. In that case let's give Friday a try. If it doesn't work, we can always revisit 🙂

**Comment by jakirkham** [comment]
As noted last week, we are going to try to reschedule so we can get a time where a few more folks are able to make it. This week the time will stay the same, but the goal is to change this for next week. Used whenisgood to put together a range of times in UTC (link below). Please fill this out by week's end so we can schedule our call for next week. Thanks! 😄

Poll: https://whenisgood.net/xbb2j88

**Comment by jakirkham** [comment]
We are in this Zoom room for this week.

https://us04web.zoom.us/j/6865884102?pwd=OFBORW5XSlFWaE1qSVN0RE5USHRkdz09

**Comment by jpivarski** [comment]
Hi everyone,

I'd like to get more involved in this (with regard to https://github.com/zarr-developers/zarr-specs/issues/62#issuecomment-663806833). I'm on the zarr-developers/community Gitter, and I take it that you decided on a Friday time for this meeting. I could try to join the next one (October 16?) if they're open to external people like me.

What time are they? 5pm in the UK? Thanks!

**Comment by jakirkham** [comment]
Hey Jim, probably the thing to do would be to drop by the community call. Details are posted here ( https://github.com/zarr-developers/community/issues/1 ). The next one would be next Wednesday, October 7th.

**Comment by jpivarski** [comment]
Aha: "community conference calls (Open to all)" as opposed to "high bandwidth call". Thanks!

**Comment by jakirkham** [comment]
No worries. Not that you wouldn't be welcome to this one. Just that it is probably less interesting (at least when joining initially).

**Comment by jakirkham** [comment]
> As noted last week, we are going to try to reschedule so we can get a time where a few more folks are able to make it. This week the time will stay the same, but the goal is to change this for next week. Used whenisgood to put together a range of times in UTC (link below). Please fill this out by week's end so we can schedule our call for next week. Thanks! 😄
> 
> Poll: https://whenisgood.net/xbb2j88

Based on [the responses]( https://whenisgood.net/xbb2j88/results/tkbpwkr ), there is no 1 time that works for everyone, but the most agreeable time seems to be 1400 UTC on Friday. So would suggest we go with that.

**Comment by Carreau** [comment]
Reminder, link was changed to the following as now zoom requires a password to join, or enable the waiting room. 

Topic: Zarr v3 dev
Time: Oct 9, 2020 02:00 PM Universal Time UTC

Join Zoom Meeting
https://us02web.zoom.us/j/89587548300?pwd=Z045VEdJWUM4UjgwaEcxUnV2UHVPdz09

Meeting ID: 895 8754 8300
Passcode: 024214
Find your local number: https://us02web.zoom.us/u/kdit3KfoKe

**Comment by alimanfoo** [comment]
We've had some difficulty finding a time when everyone actively contributing to the v3 spec development can join a meeting. 

After discussion on the community call today, we discussed whether a better model would be to work asynchronously, but for each of us to schedule in a regular time slot each week to commit to work on v3 spec development and implementations, perhaps on the same day if possible, and share that day/time with others in case there are then opportunities for more ad hoc calls/synchronisation.

For my part, I have put Fridays 4-6pm London time into my calendar, and will be doing my best to protect that. (Although I'm on leave next week 26-30 Oct).

Any thoughts/comments/objections/suggestions very welcome.

**Comment by davidbrochart** [comment]
That sounds good to me, I will try and work on Zarr v3 spec on Fridays 5-7pm Paris time, to be in sync with @alimanfoo. Most of my time during the week is on xtensor-zarr.

**Comment by joshmoore** [comment]
I've been the worst at protecting this time slot in order to make it to the calls, but I'll certainly keep trying to _end_ my weeks with the Zarr spec. Sounds like a nice way to go anyway...

**Comment by rabernat** [comment]
Hi All,

I apologize for failing to make these meetings recently. My basic excuse is
that we still have an incomplete child care situation, and I've had to
focus my limited work time on the core parts of my job (mostly supporting
students and postdocs). I do not see myself as someone who is "actively
working on the v3 spec development," so I am hoping that my absence is not
too much of a blocker.

Now that https://github.com/zarr-developers/zarr-specs/issues/101 is out, I
will do my best to participate in the process asynchronously.

Thanks to all of you who are pushing this important work forward.

Best,
Ryan

p.s. If there are specific areas where I can be helpful with this process,
please let me know.

**Comment by Carreau** [comment]
I'll still be in the call today just to make sure we do a proper wrap up until we need to meet regularly again; I don't think anybody need to apologize, those times are tough for everyone, and it's particularly hard to schedule something across 9 to 10 timezones. 

WRT the spec I suggest we look at the most recent updated issues on the zar-spec repositories, do not have to watch 100s of places. I can also try to keep the usual google doc document up to to date.

Latest issue I raise is https://github.com/zarr-developers/zarr-specs/issues/103 – non deletable stores, teh ZipStore is one of those, but this is not a case listed by the spec.

**Comment by joshmoore** [comment]
Closing this for the moment. These have been taken off the regular calendar.
