### ISSUE TITLE
Switch `master` branches to `main`

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/community#44]
Would like to suggest that we change our default branches to `main` and drop `master`. This is inline with what [GitHub itself is doing]( https://github.com/github/renaming ). Other projects are already undergoing this transition. Think this will be relatively simple for Zarr to do (though we may want to check if `master` is hard-coded anywhere). Thoughts? 🙂

- [ ] zarr-python ( https://github.com/zarr-developers/zarr-python/pull/1033 )
- [x] numcodecs ( https://github.com/zarr-developers/numcodecs/pull/322 )
- [x] numcodecs-feedstock
- [x] zarr-feedstock
- [x] zarr-paper
- [x] governance ( https://github.com/zarr-developers/governance/pull/30 )
- [x] zarr_implementations ( https://github.com/zarr-developers/zarr_implementations/pull/55 )
- [x] zarr-developers.github.io ( https://github.com/zarr-developers/zarr-developers.github.io/pull/50 )
- [x] community
- [x] steering-council
- [x] EOSS-quantstack
- [x] jobs-board
- [x] zarr-specs
- [x] .github
- [x] zarr-logo
- [x] zarr.dev
- [x] blog
- [x] gsoc

**Comment by joshmoore** [comment]
It's definitely hard-coded in a few places (workflows, readthedocs configuration, etc.) but in doing it elsewhere, I've never run into a true blocker. :+1:

**Comment by jakirkham** [comment]
conda-forge is the hardest case I've seen (lots of reasons for that). Though that just means things move more slowly. I don't think we have the same kind of issues as there though.

**Comment by joshmoore** [comment]
Added a checklist with the completed repos marked off.

**Comment by joshmoore** [comment]
An example of links that are a bit trickier:

```
zarr-governance $ git grep master
CODE_OF_CONDUCT.md:https://github.com/zarr-developers/.github/blob/master/CODE_OF_CONDUCT.md
CORE_DEV_GUIDE.md:with the [general contributor guide](https://github.com/zarr-developers/.github/blob/master/CONTRIBUTING.md).
CORE_DEV_GUIDE.md:[Code of Conduct](https://github.com/zarr-developers/.github/blob/master/CODE_OF_CONDUCT.md).
CORE_DEV_GUIDE.md:-  Our [contributor guide](https://github.com/zarr-developers/.github/blob/master/CONTRIBUTING.md).
CORE_DEV_GUIDE.md:-  Our [code of conduct](https://github.com/zarr-developers/.github/blob/master/CODE_OF_CONDUCT.md).
GOVERNANCE.md:as well as the [Code of Conduct](https://github.com/zarr-developers/.github/blob/master/CODE_OF_CONDUCT.md).
```
but supposedly GitHub redirects. Testing now.

**Comment by jakirkham** [comment]
[Relative links]( https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes ) can also point to the same locations, but avoid direct branch references

**Comment by joshmoore** [comment]
> [Relative links](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) can also point to the same locations, but avoid direct branch references

Between repositories?

**Comment by jakirkham** [comment]
That's fair. Probably not

**Comment by joshmoore** [comment]
Ah, there is! `HEAD`:

https://github.com/zarr-developers/.github/blob/HEAD/CODE_OF_CONDUCT.md

**Comment by jakirkham** [comment]
TIL 😀

**Comment by joshmoore** [comment]
Changed zarr-specs to use "main" after merging the 3.0-dev branch.

**Comment by jakirkham** [comment]
Have switched a bunch of repos over. Think it would be good if someone looked at how to do this for the webpage repo. Going to add PRs to numcodecs and zarr-python

**Comment by jakirkham** [comment]
Also it is worth noting that when using the rename branch feature on GitHub it automatically handles redirection for us. So links pointing to `master` will redirect to `main`. Not that we shouldn't go back and update them, but we should feel more comfortable making the change

**Comment by jakirkham** [comment]
Opened PRs for everything but the webpage repo

**Comment by jakirkham** [comment]
So did a test run of updating GitHub pages by using `zarr_implementations` as a guinea pig. This should help with the webpage repo.

The key takeaway is once we have a PR up to fix the webpage repo, we should rename the branch to `main` before merging it. That way GitHub pages will redeploy on merge using `main`.

Did the opposite order with `zarr_implementations` and had to create a trivial PR ( https://github.com/zarr-developers/zarr_implementations/pull/56 ) to merge and redeploy. This shouldn't be needed if we rename the branch to `main` before merging the PR there.

**Comment by jakirkham** [comment]
Didn't see any `master` references in the webpage repo (outside of external links that haven't been fixed). So just went with a trivial change in PR ( https://github.com/zarr-developers/zarr-developers.github.io/pull/50 ). Handled the branch renaming beforehand and merged. Seems to have redeployed the page and is working. Though please let me know if you spot any issue and can take another look

**Comment by jakirkham** [comment]
Last change needed is PR ( https://github.com/zarr-developers/zarr-python/pull/1033 ) and then this is done! 🎉

**Comment by MSanKeys963** [comment]
Thanks for taking care of this @jakirkham. 🙌🏻

**Comment by jakirkham** [comment]
Thanks Josh for getting the ball rolling 😄

It's always possible there are lingering issues. Feel free to raise issues on the respective repos and xref this issue

**Comment by joshmoore** [comment]
🕺🏽
