### ISSUE TITLE
Relax branch up-to-date requirement

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/community#53]
Currently we require branches stay up-to-date in PRs. However this creates a bit of strain as any time a PR is merged, all other PRs are out-of-date and need to be updated again. This also eats up more CI time and generally slows down merging PRs.

Think this requirement dates back to older CIs (like CircleCI), which do not test merge commits automatically (so would miss failures that would occur on merging). However [GitHub Actions tests merge commits with PRs]( https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request ). So this is no longer an issue.

Should add for simple conflicts, GitHub already makes users aware of these.

Given all of this, would we be ok turning off this requirement?

**Comment by jakirkham** [comment]
Thoughts @joshmoore @rabernat @MSanKeys963 ?

**Comment by joshmoore** [comment]
I'm happy to relax. I _think_ (or I remember previously) that that will mean the UI will no longer show a button for updating, so _if_ someone wants to merge in main, they will need to do so from the CLI.

**Comment by jakirkham** [comment]
That sounds correct. Though it looks like [GitHub fixed it so that button can always show up]( https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/#always-have-the-option-to-update ):

> A new repository setting lets admins opt into having the Update branch button always available whenever a pull request's branch is not up to date with the base branch. Previously, this button was only available when the Require branches to be up to date before merging branch protection setting was enabled.
>
> Repository admins and maintainers can manage the Always suggest updating pull request branches setting from the Pull Requests section in repository settings.

Went ahead and ticked this box in both Numcodecs & Zarr-Python. Also tried disabling (and then reenabling) the up-to-date branch requirement on Numcodecs to confirm this setting allowed the "Update branch" button to appear.

FWIW it is under "Settings" > "General" and then scroll to "Pull Requests" an it shows up down there.

**Comment by MSanKeys963** [comment]
I'm good with turning off the requirement. I was also thinking of informing the community about this change in one of our community calls.

**Comment by jakirkham** [comment]
Would you prefer to wait before making the change or would it be ok to go ahead (given it is already a public issue)?

**Comment by MSanKeys963** [comment]
Let's run this once through the community meeting and get everyone's thoughts before finalising it.

**Comment by joshmoore** [comment]
Considering not everyone can make it to the community calls likely agreements (or lack of vetoes) on GH is probably more inclusive. If need be, we could provide a biweekly summary (tweet/gitter/blog/...) before the community calls, since changes like this are always reversible if there are objections.

**Comment by MSanKeys963** [comment]
I was thinking more of an announcement during the community call to see if anyone has any counter to this decision and that everyone is not surprised by the change.

But I agree with @joshmoore comment, and we can go with that too!

**Comment by joshmoore** [comment]
:+1: for communicating but also :+1: for moving forward when/where we can and rollback if necessary. (Note also that we can always refer to or even update the ["Decision Making Process"](https://github.com/zarr-developers/governance/blob/main/GOVERNANCE.md#decision-making-process))

**Comment by jakirkham** [comment]
Just want to make sure I understand correctly. Are we ok making this change or is there something else that needs to happen first here?

**Comment by joshmoore** [comment]
From my POV, GFI.

**Comment by jakirkham** [comment]
Have gone ahead and made this change. Thanks all! 🙏
