### ISSUE TITLE
Zarr Office Hours

### ISSUE THREAD

**Issue by sanketverma1704** [zarr-developers/community#62]
Hi all. 👋🏻 

I announced initiating the Zarr office hours during this week's [community call](https://zarr.dev/community-calls/2023/2023-03-22.html). The office hours aim to better engage with the Zarr community and also help understand the `.zarr` storage format to anyone new to the format and community.

I'll mainly talk about the specification, the implementations, what's new in the Zarr ecosystem these days, how you can get involved and answer any questions related to the format and the community.

The agenda and discussions are not set in stone for now, and I'll be mostly bootstrapping the agenda and overall structure of the office hours according to the attendees' and community's needs.

The first office hours will occur on 29th March 2023 @ `23:30 IST/20:00 CET/19:00 BT/14:00 EDT/11:00 PDT`. We'll meet for an hour. The office hours will be repeated bi-weekly; more updates will follow.

Thoughts/suggestions/tips are most welcome. Thanks!

**Comment by sanketverma1704** [comment]
Zarr Office Hours details are here: https://zarr.dev/office-hours.

I've been successfully running them for the last few months. If there's any feedback, please ping on this issue.

For now, I'm closing this. Thanks, everyone!

**Comment by joshmoore** [comment]
Hurrah for closed (& implemented) issues! :tada:
