### ISSUE TITLE
Chat platform discussions

### ISSUE THREAD

**Issue by sanketverma1704** [zarr-developers/community#68]
Hi everyone! 👋🏻 

In the last community meeting of 2023 (meeting notes [here](https://zarr.dev/community-calls/2023/2023-12-13.html)), we discussed moving away from the existing chat platform in use, i.e. [Gitter](https://gitter.im/zarr-developers/community). There are several reasons to move away from Gitter, but the main reason is the all-time low activity.

Recently, I've been posting the announcements messages on Gitter for community and ZEP meetings, office hours, etc. Apart from my messages, our Gitter channel is pretty silent. We rarely see the community interacting with us Gitter. Has everyone moved away from using Gitter or something else?

Various options were proposed in the past, like Discord, Slack, ZulipChat, Mattermost, etc. I personally use Discord a lot, but I'm hesitant about migrating to Discord. There are several issues I see if we migrate to Discord:

- You'd need an account to read messages and participate in Discord servers
- The information on Discord cannot be linked from across the web
- Search engines do not index the messages on Discord, so no archives

Here's an article which goes into depth: https://alexn.org/blog/2022/04/09/scala-gitter-discord-mistake/.

One of the options favoured the most is using ZulipChat. We realised that some of our community members are already using ZulipChat and are well-versed in it. This also helps reduce friction when migrating users from Gitter to ZulipChat. I have been part of https://imagesc.zulipchat.com/ for almost three months, and I like it.

If there are no objections from anyone to migrating to ZulipChat, there are a couple of options we can look at:

- Join an existing server hosted by [NumFOCUS](https://numfocus.org/) or [OSSCi](https://opensource.science/)
- Create our own ZulipChat room, which could be something like https://zarr.zulipchat.com/

If we join the NF/OSSCi server, we can leverage the existing user base from various projects. I'm sceptical of the admin privileges given to Zarr maintainers in a shared space if we ever need to ban/unban someone for violating CoC. 
 
On the other hand, we'll have complete control of our room, but we'd need to invite the community and bring them our space explicitly.

Please let me know your thoughts. Thanks!

CC'ing folks who might be interested in this conversation: @joshmoore @d-v-b @normanrz @jbms @WardF @jhamman @jakirkham @rabernat

**Comment by d-v-b** [comment]
I'm happy with Zulip! I don't have a preference for joining an existing server vs creating our own. This might be a question that depends on the usage we anticipate. Gitter is pretty sparsely trafficked, so if we extrapolate from that, then joining a larger server makes sense.

**Comment by d-v-b** [comment]
Could we move forward with using Zulip? We are discussing V3 refactor stuff over in the ScientificPython discord server, but I feel like some of these discussions would be a great fit for zulip threads.

In one of our community meetings, it seemed like there was broad agreement (or broad lack of disagreement) for using a zulip chat hosted by some other entity (I don't remember which entity that was -- something IBM-adjacent?).  It would be a big improvement over gitter, and I worry that fragmented developer communication is going to be a source of friction going forward.

**Comment by sanketverma1704** [comment]
Thanks for the feedback and patience, @d-v-b.

After talking to good humans at OSSCi, we were able to set up the Zulip chat server and make it open for everyone, which means everyone can join the server without an invite.

The server is hosted at https://ossci.zulipchat.com/, and I've added https://github.com/zarr-developers/blog/pull/45 for the announcement.

Once the announcement is made, we'd need to replace the Gitter link with Zulip and start deprecating the Gitter chat room by pointing folks to the Zulip server.

**Comment by sanketverma1704** [comment]
We've successfully migrated from Gitter to Zulip! 🚀 

Thanks, everyone! Closing this now.

**Comment by joshmoore** [comment]
A few more recent updates on this front in case this decision needs reconsidering:

 - The ossci zulip has not had much uptake by other projects (and the Zarr channels have variable uptake as well)
 - e.g. @TomNicholas mentioned that VirtualiZarr conversations are taking place on slack rather than zulip
 - @sanketverma1704 mentioned that NumFOCUS slack is moving to zulip (see https://numfocus.github.io/numfocus-board/2025/20250121/ )

Discuss 😄
